server:
  port: 9000
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    schema: classpath:schema.sql #这里的: 后不能跟空格
    data: classpath:data.sql
    platform: h2
  jackson:
    serialization: 
      fail-on-empty-beans: false #设置FAIL_ON_EMPTY_BEANS属性，告诉Jackson空对象不要抛异常, 在使用了getOne时使用，这里可以删除；
  application:
    name: userAdmin
logging:
  level: 
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    cn.chinotan: DEBUG
eureka:
  client:
    healthcheck: true
    enabled: true
    service-url: 
      defaultZone: http://root:root@localhost:10000/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    