server:
  port: 8000
spring:
  application:
    name: movieAdmin
eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    service-url: 
      defaultZone: http://root:root@localhost:10000/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒）
    metadata-map: 
      zone: abc
      chinotan: chino
feign:
  hystrix:
    enabled: true # 这个版本必须加这个
    