server:
  port: 8080
spring:
  application:
    name: userAdmin
logging:
  level: 
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    cn.chinotan: DEBUG