spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/narutoform/springCloudConfig
          clone-on-start: true
   
# 也可以在repos里写          
#repos:
#  simple: https://git.oschina.net/it-much/simple
#  special:
#   pattern: special*/dev*,special*/test*
#    uri: https://git.oschina.net/it-much/special
#    cloneOnStart: false