server:
  port: 20000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/narutoform/springCloudConfig
security:
  user:
    name: chinotan
    password: chinotan